/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.50
 * Generated at: 2020-01-22 06:43:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.sjproject.member.model.vo.Member;

public final class signUpForm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/views/member/../common/header.jsp", Long.valueOf(1579072799414L));
    _jspx_dependants.put("/WEB-INF/views/member/../common/footer.jsp", Long.valueOf(1578635186000L));
    _jspx_dependants.put("/WEB-INF/views/member/../common/nav.jsp", Long.valueOf(1579570133858L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.kh.sjproject.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("<style>\r\n");
      out.write("/* number 태그 화살표 제거 */\r\n");
      out.write("input[type=\"number\"]::-webkit-outer-spin-button, input[type=\"number\"]::-webkit-inner-spin-button\r\n");
      out.write("   {\r\n");
      out.write("   -webkit-appearance: none;\r\n");
      out.write("   margin: 0;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("\r\n");

	String msg = (String)session.getAttribute("msg");
	Member loginMember = (Member)session.getAttribute("loginMember");
	String signMsg = (String)session.getAttribute("signMsg");
	// c6). 쿠키 사용을 위한 변수 생성
	boolean save = false; // 아이디 저장 체크박스 값을 수정하기 위한 변수
	String saveId = "";   // 쿠키에 저장된 saveId라는 키가 가지고 있는 값을 저장할 변수 
	Cookie[] cookies = request.getCookies(); // 전달받은 쿠키 저장
	
	// 서버 첫 시작시 request.getCookies()의 값이 null
	// -> if문으로 처리하지 않는 경우 페이지 로딩 시 nullPointerException이 발생됨.
	if(cookies != null){
		for(Cookie c : cookies){
			
			// 쿠키 객체에서 name을 얻어와 그 값이 saveId와 같은지 비교한다. 
			//          == key, 속성
			if(c.getName().equals("saveId")){
				
				saveId = c.getValue(); // 현재 쿠키의 값이 꺼내어져 saveId에 저장됨.
				save = true;
			}
		}
	}

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"UTF-8\">\r\n");
      out.write("\t<meta name=\"viewport\"\r\n");
      out.write("\t\tcontent=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\r\n");
      out.write("\t<link rel=\"stylesheet\"\r\n");
      out.write("\t\thref=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css\"\r\n");
      out.write("\t\tintegrity=\"sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// 로그인 실패 메시지 출력 후\r\n");
      out.write("\t\t// session에 남아있는 \"msg\" 속성 제거\r\n");
      out.write("\t\t");
 if(msg != null) {
      out.write(" // 로그인 실패한 경우\r\n");
      out.write("\t\t\t\talert(\"");
      out.print( msg );
      out.write("\");\r\n");
      out.write("\t\t");
 }
			session.removeAttribute("msg");
		
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// 회원가입을 진행하였을 경우\r\n");
      out.write("\t\t");
 if(signMsg != null) {
      out.write("\r\n");
      out.write("\t\t\t\talert(\"");
      out.print( signMsg );
      out.write("\");\r\n");
      out.write("\t\t");
 }
			session.removeAttribute("signMsg");
		
      out.write("\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"blog-header\">\r\n");
      out.write("\t\t<div\r\n");
      out.write("\t\t\tclass=\"row flex-nowrap justify-content-between align-items-center\">\r\n");
      out.write("\t\t\t<div class=\"col-4 pt-1\">\r\n");
      out.write("\t\t\t\t<a class=\"text-muted\" href=\"");
      out.print( request.getContextPath() );
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t<!-- 서버ip:8080/sjproject -->\r\n");
      out.write("\t\t\t\t\t<img src=\"https://www.iei.or.kr/resources/images/common/top_logo.jpg\"\r\n");
      out.write("\t\t\t\t\t\theight=\"60px\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<!-- 로그인이 되어있지 않은 경우 start -->\r\n");
      out.write("\t\t\t");
 if(loginMember == null) { 
      out.write("\r\n");
      out.write("\t\t\t<div class=\"col-4 d-flex justify-content-end align-items-center\">\r\n");
      out.write("\t\t\t\t<a id=\"modal-120930\" href=\"#modal-container-120930\" role=\"button\"\r\n");
      out.write("\t\t\t\t\tclass=\"btn btn-sm btn-outline-secondary\" data-toggle=\"modal\">로그인</a>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<div class=\"modal fade\" id=\"modal-container-120930\" role=\"dialog\"\r\n");
      out.write("\t\t\t\t\taria-labelledby=\"myModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"modal-title\" id=\"myModalLabel\">로그인 모달창</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">×</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-body\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<form class=\"form-signin\" method=\"POST\" \r\n");
      out.write("\t\t\t\t\t\t\t\taction=\"");
      out.print( request.getContextPath());
      out.write("/member/login.do\"\r\n");
      out.write("\t\t\t\t\t\t\t\tonsubmit=\"return loginValidate();\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" id=\"memberId\" name=\"memberId\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"아이디\" value=\"");
      out.print( saveId );
      out.write("\"> <br> \r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"password\" class=\"form-control\" id=\"memberPwd\" name=\"memberPwd\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\tplaceholder=\"비밀번호\"> <br>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<div class=\"checkbox mb-3\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t<label> <input type=\"checkbox\" id=\"save\" name=\"save\" ");
      out.print( save ? "checked" : "" );
      out.write(" >아이디 저장 </label>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<button class=\"btn btn-lg btn-primary btn-block\" type=\"submit\">로그인</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<a class=\"btn btn-lg btn-secondary btn-block\" href=\"");
      out.print(request.getContextPath());
      out.write("/member/signUpForm.do\">회원가입</a>\r\n");
      out.write("\t\t\t\t\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Close</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<!-- 로그인이 되어있지 않은 경우 end -->\r\n");
      out.write("\t\t\t");
 } else { 
      out.write("\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"d-flex justify-content-end align-items-center\">\r\n");
      out.write("\t\t\t\t");
      out.print( loginMember.getMemberName() );
      out.write("님 환영합니다. &nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath() );
      out.write("/member/mypage.do\" role=\"button\" class=\"btn btn-sm btn-outline-secondary\">마이페이지</a>\r\n");
      out.write("\t\t\t\t&nbsp;\r\n");
      out.write("\t\t\t\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/member/logout.do\" role=\"button\" class=\"btn btn-sm btn-outline-secondary\">로그아웃</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</header>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t// 로그인 유효성 검사\r\n");
      out.write("\t\tfunction loginValidate(){\r\n");
      out.write("\t\t\t// trim() : 문자열 앞뒤 공백 제거\r\n");
      out.write("\t\t\tif( $(\"#memberId\").val().trim().length==0){\r\n");
      out.write("\t\t\t\talert(\"아이디를 입력하세요.\");\r\n");
      out.write("\t\t\t\t$(\"#memberId\").focus();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tif( $(\"#memberPwd\").val().trim().length==0){\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 입력하세요.\");\r\n");
      out.write("\t\t\t\t$(\"#memberPwd\").focus();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("\t<script\r\n");
      out.write("\t\tsrc=\"https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js\"\r\n");
      out.write("\t\tintegrity=\"sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6\"\r\n");
      out.write("\t\tcrossorigin=\"anonymous\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <nav class=\"nav-scroller py-1 mb-2\">\r\n");
      out.write("      <ul class=\"nav justify-content-center\">\r\n");
      out.write("        <li class=\"nav-item col-md text-center\">\r\n");
      out.write("          <a class=\"nav-link active\" href=\"");
      out.print( request.getContextPath());
      out.write("/notice/list\">공지사항</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item col-md text-center\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"");
      out.print( request.getContextPath());
      out.write("/board/list\">게시판</a>\r\n");
      out.write("        </li>\r\n");
      out.write("        <li class=\"nav-item col-md text-center\">\r\n");
      out.write("          <a class=\"nav-link\" href=\"#\">Q & A</a>\r\n");
      out.write("        </li>\r\n");
      out.write("      </ul>\r\n");
      out.write("    </nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("      <div class=\"py-5 text-center\">\r\n");
      out.write("         <h2>회원 가입</h2>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"row\">\r\n");
      out.write("         <div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("\r\n");
      out.write("            <form method=\"POST\" action=\"signUp.do\" class=\"needs-validation\"\r\n");
      out.write("               name=\"signUpForm\" onsubmit=\"return validate();\">\r\n");
      out.write("               ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <!-- 아이디 -->\r\n");
      out.write("               <div class=\"row mb-3 form-row\">\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <label for=\"id\">* 아이디</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                     <input type=\"text\" class=\"form-control\" name=\"id\" id=\"id\"\r\n");
      out.write("                        maxlength=\"12\" placeholder=\"아이디를 입력하세요\" autocomplete=\"off\"\r\n");
      out.write("                        required> \r\n");
      out.write("                     <!-- required : 필수 입력 항목으로 지정 -->\r\n");
      out.write("                     <!-- autocomplete=\"off\" : input 태그 자동완성 기능을 끔 -->\r\n");
      out.write("                  </div>\r\n");
      out.write("                  \r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("                     <span id=\"checkId\">&nbsp;</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("               <!-- 비밀번호 -->\r\n");
      out.write("               <div class=\"row mb-3 form-row\">\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <label for=\"pwd1\">* 비밀번호</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                     <input type=\"password\" class=\"form-control\" id=\"pwd1\" name=\"pwd1\"\r\n");
      out.write("                        maxlength=\"12\" placeholder=\"비밀번호를 입력하세요\" required>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("                     <span id=\"checkPwd1\">&nbsp;</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <!-- 비밀번호 확인 -->\r\n");
      out.write("               <div class=\"row mb-3 form-row\">\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <label for=\"pwd2\">* 비밀번호 확인</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                     <input type=\"password\" class=\"form-control\" id=\"pwd2\"\r\n");
      out.write("                        maxlength=\"12\" placeholder=\"비밀번호 확인\" required>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("                     <span id=\"checkPwd2\">&nbsp;</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <br>\r\n");
      out.write("\r\n");
      out.write("               <!-- 이름 -->\r\n");
      out.write("               <div class=\"row mb-3 form-row\">\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <label for=\"name\">* 이름</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                     <input type=\"text\" class=\"form-control\" id=\"name\" name=\"name\"\r\n");
      out.write("                        required>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("                     <span id=\"checkName\">&nbsp;</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <!-- 전화번호 -->\r\n");
      out.write("               <div class=\"row mb-3 form-row\">\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <label for=\"phone1\">* 전화번호</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <!-- 전화번호1 -->\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <select class=\"custom-select\" id=\"phone1\" name=\"phone1\" required>\r\n");
      out.write("                        <option>010</option>\r\n");
      out.write("                        <option>011</option>\r\n");
      out.write("                        <option>016</option>\r\n");
      out.write("                        <option>017</option>\r\n");
      out.write("                        <option>019</option>\r\n");
      out.write("                     </select>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <!-- 전화번호2 -->\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <input type=\"number\" class=\"form-control phone\" id=\"phone2\"\r\n");
      out.write("                        maxlength=\"4\" name=\"phone2\" required>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <!-- 전화번호3 -->\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <input type=\"number\" class=\"form-control phone\" id=\"phone3\"\r\n");
      out.write("                        maxlength=\"4\" name=\"phone3\" required>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("                     <span id=\"checkPhone\">&nbsp;</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <!-- 이메일 -->\r\n");
      out.write("               <div class=\"row mb-3 form-row\">\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <label for=\"email\">* Email</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-6\">\r\n");
      out.write("                     <input type=\"email\" class=\"form-control\" id=\"email\" name=\"email\"\r\n");
      out.write("                        autocomplete=\"off\" required>\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                  <div class=\"col-md-6 offset-md-3\">\r\n");
      out.write("                     <span id=\"checkEmail\">&nbsp;</span>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("               <br>\r\n");
      out.write("\r\n");
      out.write("               <!-- 주소 -->\r\n");
      out.write("               <!-- 오픈소스 도로명 주소 API -->\r\n");
      out.write("               <!-- https://www.poesis.org/postcodify/ -->\r\n");
      out.write("               <div class=\"row mb-3 form-row\">\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <label for=\"postcodify_search_button\">우편번호</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <input type=\"text\" name=\"post\"\r\n");
      out.write("                        class=\"form-control postcodify_postcode5\">\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <button type=\"button\" class=\"btn btn-primary\"\r\n");
      out.write("                        id=\"postcodify_search_button\">검색</button>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"row mb-3 form-row\">\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <label for=\"address1\">도로명 주소</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-9\">\r\n");
      out.write("                     <input type=\"text\" class=\"form-control postcodify_address\"\r\n");
      out.write("                        name=\"address1\" id=\"address1\">\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <div class=\"row mb-3 form-row\">\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <label for=\"address2\">상세주소</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-9\">\r\n");
      out.write("                     <input type=\"text\" class=\"form-control postcodify_details\"\r\n");
      out.write("                        name=\"address2\" id=\"address2\">\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <!-- jQuery와 postcodify 를 로딩한다. -->\r\n");
      out.write("               <script src=\"//d1p7wdleee1q2z.cloudfront.net/post/search.min.js\"></script>\r\n");
      out.write("               <script>\r\n");
      out.write("                  // 검색 단추를 누르면 팝업 레이어가 열리도록 설정한다.\r\n");
      out.write("                  $(function() {\r\n");
      out.write("                     $(\"#postcodify_search_button\").postcodifyPopUp();\r\n");
      out.write("                  });\r\n");
      out.write("               </script>\r\n");
      out.write("\r\n");
      out.write("               <!-- 관심분야 -->\r\n");
      out.write("               <hr class=\"mb-4\">\r\n");
      out.write("               <div class=\"row\">\r\n");
      out.write("                  <div class=\"col-md-3\">\r\n");
      out.write("                     <label>관심 분야</label>\r\n");
      out.write("                  </div>\r\n");
      out.write("                  <div class=\"col-md-9 custom-control custom-checkbox\">\r\n");
      out.write("                     <div class=\"form-check form-check-inline\">\r\n");
      out.write("                        <input type=\"checkbox\" name=\"memberInterest\" id=\"sports\"\r\n");
      out.write("                           value=\"운동\" class=\"form-check-input custom-control-input\">\r\n");
      out.write("                        <label class=\"form-check-label custom-control-label\"\r\n");
      out.write("                           for=\"sports\">운동</label>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"form-check form-check-inline\">\r\n");
      out.write("                        <input type=\"checkbox\" name=\"memberInterest\" id=\"movie\"\r\n");
      out.write("                           value=\"영화\" class=\"form-check-input custom-control-input\">\r\n");
      out.write("                        <label class=\"form-check-label custom-control-label\" for=\"movie\">영화</label>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"form-check form-check-inline\">\r\n");
      out.write("                        <input type=\"checkbox\" name=\"memberInterest\" id=\"music\"\r\n");
      out.write("                           value=\"음악\" class=\"form-check-input custom-control-input\">\r\n");
      out.write("                        <label class=\"form-check-label custom-control-label\" for=\"music\">음악</label>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <br>\r\n");
      out.write("                     <div class=\"form-check form-check-inline\">\r\n");
      out.write("                        <input type=\"checkbox\" name=\"memberInterest\" id=\"cooking\"\r\n");
      out.write("                           value=\"요리\" class=\"form-check-input custom-control-input\">\r\n");
      out.write("                        <label class=\"form-check-label custom-control-label\"\r\n");
      out.write("                           for=\"cooking\">요리</label>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"form-check form-check-inline\">\r\n");
      out.write("                        <input type=\"checkbox\" name=\"memberInterest\" id=\"game\"\r\n");
      out.write("                           value=\"게임\" class=\"form-check-input custom-control-input\">\r\n");
      out.write("                        <label class=\"form-check-label custom-control-label\" for=\"game\">게임</label>\r\n");
      out.write("                     </div>\r\n");
      out.write("                     <div class=\"form-check form-check-inline\">\r\n");
      out.write("                        <input type=\"checkbox\" name=\"memberInterest\" id=\"etc\" value=\"기타\"\r\n");
      out.write("                           class=\"form-check-input custom-control-input\"> <label\r\n");
      out.write("                           class=\"form-check-label custom-control-label\" for=\"etc\">기타</label>\r\n");
      out.write("                     </div>\r\n");
      out.write("                  </div>\r\n");
      out.write("               </div>\r\n");
      out.write("\r\n");
      out.write("               <hr class=\"mb-4\">\r\n");
      out.write("               <button class=\"btn btn-primary btn-lg btn-block\" type=\"submit\">가입하기</button>\r\n");
      out.write("            </form>\r\n");
      out.write("         </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <br> <br>\r\n");
      out.write("\r\n");
      out.write("      <script>\r\n");
      out.write("         // 각 유효성 검사 결과를 저장할 객체\r\n");
      out.write("         var signUpCheck = {\r\n");
      out.write("            \"id\" : false,\r\n");
      out.write("            \"idDup\" : false,\r\n");
      out.write("            \"pwd1\" : false,\r\n");
      out.write("            \"pwd2\" : false,\r\n");
      out.write("            \"name\" : false,\r\n");
      out.write("            \"phone\" : false,\r\n");
      out.write("            \"email\" : false\r\n");
      out.write("         };\r\n");
      out.write("\r\n");
      out.write("         // 실시간 입력 형식 검사\r\n");
      out.write("         // 정규표현식\r\n");
      out.write("         $(document).ready(\r\n");
      out.write("               function() {\r\n");
      out.write("\r\n");
      out.write("                  // jQuery 변수 : 변수에 직접적으로 jQuery메소드를 사용할 수 있음.\r\n");
      out.write("                  var $id = $(\"#id\");\r\n");
      out.write("                  var $pwd1 = $(\"#pwd1\");\r\n");
      out.write("                  var $pwd2 = $(\"#pwd2\");\r\n");
      out.write("                  var $name = $(\"#name\");\r\n");
      out.write("                  var $phone2 = $(\"#phone2\");\r\n");
      out.write("                  var $phone3 = $(\"#phone3\");\r\n");
      out.write("                  var $email = $(\"#email\");\r\n");
      out.write("\r\n");
      out.write("                  // 아이디  유효성 검사\r\n");
      out.write("                  // 첫글자는 영어 소문자, 나머지 글자는 영어 대,소문자 + 숫자, 총 6~12글자\r\n");
      out.write("                  $id.on(\"input\", function() {\r\n");
      out.write("                     var regExp = /^[a-z][a-zA-z\\d]{5,11}$/;\r\n");
      out.write("                     if (!regExp.test($id.val())) {\r\n");
      out.write("                        $(\"#checkId\").text(\"아이디 형식이 유효하지 않습니다.\").css(\r\n");
      out.write("                              \"color\", \"red\");\r\n");
      out.write("\r\n");
      out.write("                        signUpCheck.id = false;\r\n");
      out.write("\r\n");
      out.write("                     } else {\r\n");
      out.write("                        signUpCheck.id = true;\r\n");
      out.write("                        // 유효x, 사용x, 사용o\r\n");
      out.write("                        \r\n");
      out.write("                        // ajax를 이용한 실시간 아이디 중복검사\r\n");
      out.write("                        $.ajax({\r\n");
      out.write("                        \t\r\n");
      out.write("                        \turl : \"idDupCheck.do\",\r\n");
      out.write("                        \t\r\n");
      out.write("                        \tdata : {id : $id.val()},\r\n");
      out.write("                        \t\r\n");
      out.write("                        \ttype : \"GET\",\r\n");
      out.write("                        \t\r\n");
      out.write("                        \tsuccess : function(result){\r\n");
      out.write("                        \t\t\r\n");
      out.write("                        \t\tif(result == \"yes\"){\r\n");
      out.write("                        \t\t\t$(\"#checkId\").text(\"사용 가능한 아이디 입니다.\").css(\r\n");
      out.write("                                            \"color\", \"green\");\r\n");
      out.write("                        \t\t\t\r\n");
      out.write("                        \t\t\tsignUpCheck.idDup = true;\r\n");
      out.write("                        \t\t}else{\r\n");
      out.write("                        \t\t\t$(\"#checkId\").text(\"사용 할 수 없는 아이디 입니다.\").css(\r\n");
      out.write("                                            \"color\", \"red\");\r\n");
      out.write("                        \t\t\t\r\n");
      out.write("                        \t\t\tsignUpCheck.idDup = false;\r\n");
      out.write("                        \t\t}\r\n");
      out.write("                        \t\t\r\n");
      out.write("                        \t\t\r\n");
      out.write("                        \t},\r\n");
      out.write("                        \t\r\n");
      out.write("                        \terror : function(e){\r\n");
      out.write("                        \t\tconsole.log(\"아이디 중복검사 ajax 실패\");\r\n");
      out.write("                        \t\tconsole.log(e);\r\n");
      out.write("                        \t},\r\n");
      out.write("                        \t\r\n");
      out.write("                        });\r\n");
      out.write("                        \r\n");
      out.write("                        \r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("\r\n");
      out.write("                 /* // 아이디 중복 체크창 오픈\r\n");
      out.write("                  $(\"#idDupCheck\").click(function(){\r\n");
      out.write("                \t  window.open(\"idDupForm.do\", \"idDupForm\", \"width=300, height=200\");\r\n");
      out.write("                \t  // \t\t\t팝업창 주소\t\t팝업창 이름\t\t설정\r\n");
      out.write("                  })*/\r\n");
      out.write("\r\n");
      out.write("                  // 비밀번호  유효성 검사\r\n");
      out.write("                  //영어 대,소문자 + 숫자, 총 6~12글자\r\n");
      out.write("                  $pwd1.on(\"input\", function() {\r\n");
      out.write("                     var regExp = /^[A-Za-z0-9]{6,12}$/;\r\n");
      out.write("\r\n");
      out.write("                     if (!regExp.test($pwd1.val())) {\r\n");
      out.write("                        $(\"#checkPwd1\").text(\"비밀번호 형식이 유효하지 않습니다.\")\r\n");
      out.write("                              .css(\"color\", \"red\");\r\n");
      out.write("                        signUpCheck.pwd1 = false;\r\n");
      out.write("                     } else {\r\n");
      out.write("                        $(\"#checkPwd1\").text(\"유효한 형식의 비밀번호 입니다.\").css(\r\n");
      out.write("                              \"color\", \"green\");\r\n");
      out.write("\r\n");
      out.write("                        signUpCheck.pwd1 = true;\r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("\r\n");
      out.write("                  // 비밀번호 일치 여부\r\n");
      out.write("                  $pwd2.on(\"input\", function() {\r\n");
      out.write("                     if ($pwd1.val().trim() != $pwd2.val().trim()) {\r\n");
      out.write("                        $(\"#checkPwd2\").text(\"비밀번호가 일치하지 않습니다.\").css(\r\n");
      out.write("                              \"color\", \"red\");\r\n");
      out.write("                        signUpCheck.pwd2 = false;\r\n");
      out.write("                     } else {\r\n");
      out.write("                        $(\"#checkPwd2\").text(\"비밀번호가 일치합니다.\").css(\r\n");
      out.write("                              \"color\", \"green\");\r\n");
      out.write("                        signUpCheck.pwd2 = true;\r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("\r\n");
      out.write("                  // 이름 유효성 검사\r\n");
      out.write("                  // 한글 두 글자 이상\r\n");
      out.write("                  $name.on(\"input\", function() {\r\n");
      out.write("                     var regExp = /^[가-힣]{2,}$/;\r\n");
      out.write("                     if (!regExp.test($(this).val())) {\r\n");
      out.write("                        signUpCheck.name = false;\r\n");
      out.write("                     } else {\r\n");
      out.write("                        signUpCheck.name = true;\r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("\r\n");
      out.write("                  // 전화번호 관련\r\n");
      out.write("                  $(\".phone\").on(\r\n");
      out.write("                        \"input\",\r\n");
      out.write("                        function() {\r\n");
      out.write("\r\n");
      out.write("                           // 전화번호 input 태그에 4글자 이상 입력하지 못하게 하는 이벤트\r\n");
      out.write("                           if ($(this).val().length > $(this).prop(\r\n");
      out.write("                                 \"maxLength\")) {\r\n");
      out.write("                              $(this).val(\r\n");
      out.write("                                    $(this).val().slice(\r\n");
      out.write("                                          0,\r\n");
      out.write("                                          $(this).prop(\r\n");
      out.write("                                                \"maxLength\")));\r\n");
      out.write("                           }\r\n");
      out.write("\r\n");
      out.write("                           // 전화번호 유효성 검사\r\n");
      out.write("                           var regExp2 = /^\\d{3,4}$/; // 숫자 3~4 글자\r\n");
      out.write("                           var regExp3 = /^\\d{4,4}$/; // 숫자 4 글자\r\n");
      out.write("\r\n");
      out.write("                           if (!regExp2.test($phone2.val()) || !regExp3.test($phone3.val())) {\r\n");
      out.write("                              $(\"#checkPhone\").text(\"전화번호가 유효하지 않습니다.\").css(\"color\", \"red\");\r\n");
      out.write("                              signUpCheck.phone = false;\r\n");
      out.write("                           } else {\r\n");
      out.write("                              $(\"#checkPhone\").text(\"유효한 전화번호 형식입니다.\").css(\"color\", \"green\");\r\n");
      out.write("                              signUpCheck.phone = true;\r\n");
      out.write("                           }\r\n");
      out.write("\r\n");
      out.write("                        });\r\n");
      out.write("\r\n");
      out.write("                  // 이메일 유효성 검사\r\n");
      out.write("\r\n");
      out.write("                  $email.on(\"input\", function() {\r\n");
      out.write("                     var regExp = /^[\\w]{4,}@[\\w]+(\\.[\\w]+){1,3}$/;\r\n");
      out.write("                     if (!regExp.test($email.val())) {\r\n");
      out.write("                        $(\"#checkEmail\").text(\"이메일 형식이 유효하지 않습니다.\")\r\n");
      out.write("                              .css(\"color\", \"red\");\r\n");
      out.write("\r\n");
      out.write("                        signUpCheck.email = false;\r\n");
      out.write("\r\n");
      out.write("                     } else {\r\n");
      out.write("                        $(\"#checkEmail\").text(\"유효한 형식의 이메일 입니다.\").css(\r\n");
      out.write("                              \"color\", \"green\");\r\n");
      out.write("\r\n");
      out.write("                        signUpCheck.email = true;\r\n");
      out.write("                     }\r\n");
      out.write("                  });\r\n");
      out.write("\r\n");
      out.write("               });\r\n");
      out.write("\r\n");
      out.write("         // submit 동작\r\n");
      out.write("         function validate() {\r\n");
      out.write("\r\n");
      out.write("          /*  // 아이디 중복 검사 결과\r\n");
      out.write("            if ($(\"#idDup\").val() == \"true\")\r\n");
      out.write("               signUpCheck.idDup = true;\r\n");
      out.write("            else\r\n");
      out.write("               signUpCheck.idDup = false;  */\r\n");
      out.write("\r\n");
      out.write("            for ( var key in signUpCheck) {\r\n");
      out.write("               if (!signUpCheck[key]) {\r\n");
      out.write("                  alert(\"일부 입력값이 잘못되었습니다.\");\r\n");
      out.write("                  var id = \"#\" + key;\r\n");
      out.write("                  $(id).focus();\r\n");
      out.write("                  return false;\r\n");
      out.write("               }\r\n");
      out.write("            }\r\n");
      out.write("         }\r\n");
      out.write("      </script>\r\n");
      out.write("\r\n");
      out.write("      ");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <footer class=\"text-muted\" >\r\n");
      out.write("      <div class=\"container\">\r\n");
      out.write("        <p class=\"float-right\">\r\n");
      out.write("          <a href=\"#\">Back to top</a>\r\n");
      out.write("        </p>\r\n");
      out.write("        <p>Album example is &copy; Bootstrap, but please download and customize it for yourself!</p>\r\n");
      out.write("        <p>New to Bootstrap? <a href=\"{{ site.url }}/\">Visit the homepage</a> or read our <a href=\"{{ site.baseurl }}/docs/{{ site.docs_version }}/getting-started/introduction/\">getting\r\n");
      out.write("            started guide</a>.</p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("   </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
